services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      WATCHTOWER_POLL_INTERVAL: 3600

  podfetch:
    image: samuel19982/podfetch:latest
    container_name: podfetch
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:80/tcp"
    volumes:
      - podfetch_podcasts:/app/podcasts
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://localhost:80
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: db
    hostname: db
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - podfetch_db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  podfetch_podcasts:
    name: podfetch_podcasts
    external: true
  podfetch_db:
    name: podfetch_db
    external: true
