#! /bin/sh

PROG=$0
die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
echo "Script Dir: $BASEDIR"


if [ ! -f "$BASEDIR/.env" ]; then
  DB_PWD=$(cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w 50 | head -n 1)
  {
    echo "POSTGRES_USER=podfetch"
    echo "POSTGRES_PASSWORD=$DB_PWD"
    echo "POSTGRES_DB=podfetch"
  } > "$BASEDIR/.env"
fi

echo "Create Volumes"
mkdir -p /data/db/podfetch
mkdir -p /data/podcasts

docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/db/podfetch \
  podfetch_db

docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/podcasts \
  podfetch_podcasts


echo "Start DB"
docker container stop db
docker container rm db -f
docker container run --rm --name db \
            -v podfetch_db:/var/lib/postgresql/data \
            -e "POSTGRES_PASSWORD=$DB_PWD" \
            -d postgres:14-alpine

READY=1
while [ $READY != 0 ]
do
  echo "Waiting for DB"...
  sleep 5
  docker exec -it db pg_isready -U postgres
  READY=$?
done

#docker exec -it db pg_isready -U postgres
#echo "Ready: $?"

echo "Start Create DB User"
docker exec -it db psql -U postgres -c "CREATE USER podfetch WITH PASSWORD '$DB_PWD' CREATEDB;"

echo "Stop DB"
docker container stop db
docker container rm db -f

sudo docker compose pull && sudo docker compose up -d --remove-orphans

sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="10.0.0.0/8" port protocol="tcp" port="80" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="80" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="172.16.0.0/20" port protocol="tcp" port="80" accept'
