#! /bin/sh

PROG=$0
die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
echo "Script Dir: $BASEDIR"


if [ ! -f "$BASEDIR/.env" ]; then
  DB_PWD=$(cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w 50 | head -n 1)
  {
    echo "POSTGRES_USER=podfetch"
    echo "POSTGRES_USER=$DB_PWD"
    echo "POSTGRES_DB=podfetch"
  } > "$BASEDIR/.env"
fi

echo "Create Volumes"
mkdir -p /data/db/podfetch
mkdir -p /data/podcasts

docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/db/podfetch \
  podfetch-db

docker volume create \
  --opt type=none \
  --opt o=bind \
  --opt device=/data/podcasts \
  podfetch-podcasts

sudo docker compose pull && sudo docker compose up -d --remove-orphans

sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="10.0.0.0/8" port protocol="tcp" port="80" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="80" accept'
sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="172.16.0.0/20" port protocol="tcp" port="80" accept'
